export const UPDATE_PUBLIC_KEY = "UPDATE_PUBLIC_KEY";
export const UPDATE_MNEMONIC = "UPDATE_MNEMONIC";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const SET_CONFIRMED = "SET_CONFIRMED";
