variables:
  SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

stages:
- test
- build
- test
- publish
  
test:unit:
  stage: test
  script:
  - yarn install
  - yarn test
  tags:
  - eos
  
build:
  stage: build
  script:
  - yarn install
  - yarn build
  tags:
  - eos

test:integration:
  stage: test
  script:
  - yarn install
  - yarn integration-test
  tags:
  - eos
  
publish:
  stage: publish
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
      - build/
  tags:
  - eos