language: node_js
node_js:
- "10"

script:
- yarn install
- yarn test
- curl --write-out '%{http_code}' --silent --output /dev/null -X POST -F token=$TOKEN -F ref=$TRAVIS_BRANCH -F "variables[BRANCH]=$TRAVIS_BRANCH" $URL
