export const SET_TRANSACTION_TO_SIGN = 'SET_TRANSACTION_TO_SIGN';
export const SET_TRANSACTION_AS_SIGNED = 'SET_TRANSACTION_AS_SIGNED';
export const SET_TRANSACTION_AS_DISCARDED = 'SET_TRANSACTION_AS_DISCARDED';
export const SET_TRANSACTION_AS_FINISHED = 'SET_TRANSACTION_AS_FINISHED';
export const SET_TRANSACTION_AS_FAILED = 'SET_TRANSACTION_AS_FAILED';