export const SET_PLATFORM_TO_BIND = 'SET_PLATFORM_TO_BIND';
export const SET_PLATFORM_BINDING_AS_SIGNED = 'SET_PLATFORM_BINDING_AS_SIGNED';
export const SET_PLATFORM_BINDING_AS_DISCARDED =
  'SET_PLATFORM_BINDING_AS_DISCARDED';
export const SET_PLATFORM_BINDING_AS_FINISHED =
  'SET_PLATFORM_BINDING_AS_FINISHED';
export const SET_PLATFORM_BINDING_AS_FAILED = 'SET_PLATFORM_BINDING_AS_FAILED';
